name: Publish OTA update to production

on:
  push:
    branches: [main]
    paths:
      - mobile/**

jobs:
  publish_update:
    type: update
    params:
      platform: ios
      branch: production
      message: OTA update from main
